# author is used in the atom feed
title: JBoss Technology Evangelist Workshops
author: Eric D. Schabell
description: My workshops around OpenShift, xPaaS, & Ingetration and BPM

profiles:
  development:
    base_url: http://localhost:4242
  production:
    base_url: http://presos-onthe.rhcloud.com
